### ISSUE TITLE
404 Not Found: event-stream@3.3.6

### ISSUE THREAD

**Issue by Tyki** [deliciousinsights/goal-tracker#1]
Bonjour,

Après un `npm install` sur la branche master, j'ai l'erreur suivante : 
`404 Not Found: event-stream@3.3.6`

En effet, suite à une faille qui permettait de miner des bitcoins via cette lib, cette version n'est plus sur NPM.

Est-il possible de mettre à jour le package-lock ? J'aurai bien fait une PR mais je ne connais pas les implications de faire une montée de version de event-stream vers 4.x

C'est bloquant pour l'installation du projet .

**Comment by mbrehin** [comment]
Bonjour,

Cette problématique a été résolue avec les dernières mises à jour  👍
